name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e-testing:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Linter
      run: npm run lint
      continue-on-error: true # Evita que se trabe el pipeline si tenés un warning de linter

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Build Next.js application
      run: npm run build
      env:
        NEXTAUTH_SECRET: super_secret_mock_key_123
        NEXTAUTH_URL: http://localhost:3000
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Run Playwright tests
      run: npx playwright test
      env:
        PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
        NEXT_PUBLIC_POSTHOG_KEY: phc_mock_key_for_testing
        NEXT_PUBLIC_POSTHOG_HOST: https://us.i.posthog.com
        NEXTAUTH_SECRET: super_secret_mock_key_123
        NEXTAUTH_URL: http://localhost:3000
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30